project:
  type: website
  output-dir: docs
  title: "Shefali Lathwal"

website: 
  back-to-top-navigation: true
  favicon: "images/profile.jpg"
  page-footer: 
    left: 
      - icon: envelope
        text: Contact Me
        href: "mailto:slathwal@alum.mit.edu"
    right:
      - icon: github
        text: Github for this website
        href: "https://github.com/slathwal/slathwal.github.io"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      #- talks: Talks
      #  href: talks.qmd
      #- text: Blogs
      #  href: blogs.qmd
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/in/shefali-lathwal-90bb4b44/"
      - icon: github
        href: "https://github.com/slathwal"

format:
  html:
    grid: 
      body-width: 1000px
      sidebar-width: 200px
      margin-width: 200px
    theme:
      - simplex
      - brand
    css: styles.css
    toc: true



