project:
  type: website
  output-dir: docs
  title: "Shefali Lathwal"

website: 
  back-to-top-navigation: true
  favicon: "images/profile.jpg"
  page-footer:
    #background: light
    border: false
    left: Made with [![](https://quarto.org/quarto.png){width=70px}](https://quarto.org)
    right:
      - text: "{{< fa envelope >}} Contact me"
        href: mailto:slathwal@alum.mit.edu
      - text: "{{< fa brands github >}} Source code" 
        href: "https://github.com/slathwal/slathwal.github.io"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Talks
        href: talks.qmd
      - text: Blog
        href: blogs.qmd
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/in/shefali-lathwal-90bb4b44/"
      - icon: github
        href: "https://github.com/slathwal"

format:
  html:
    grid: 
      body-width: 1000px
      sidebar-width: 250px
      margin-width: 250px
    theme:
      - yeti
    css: styles.css
    toc: true



