project:
  type: website
  output-dir: docs
  title: "Shefali Lathwal"

website: 
  navbar:
    search: true
    right:
      - text: Home
        href: index.qmd
      - text: "Blog"
      - text: "Projects"
        href: projects.qmd
    tools:
      - icon: linkedin
        href: "https://www.linkedin.com/in/shefali-lathwal-90bb4b44/"
      - icon: github
        href: "https://github.com/slathwal"

format:
  html:
    theme:
      - simplex
      - brand
    css: styles.css
    toc: true



