---
toc: true
---
<!-- Experimenting with multi-column layout in html output. The problem is that if I use a heading inside any of the tags {.columns}, {.layout} or {.layout-ncol} or {.g-col-6}, the heading does not show in the table of contents -->

```{=html}
<h1 text-align: center> Heading 1 </h1>

<iframe width="420" height="315" src="https://www.youtube.com/watch?v=s0qyxYvuMa0">
</iframe>

<div>
    A discussion with Cyclica, Altis Labs, Elucidata, and Atomwise on how to run successful machine learning projects in biotech and pharma R&D.
</div>

```

## Panel discussion: Implementing ML in biopharma R&D
{{< video https://www.youtube.com/watch?v=s0qyxYvuMa0 >}}

A discussion with Cyclica, Altis Labs, Elucidata, and Atomwise on how to run successful machine learning projects in biotech and pharma R&D.


## Framework for quality of high-dimensional biological data

{{< video https://www.youtube.com/watch?v=QYXLI58w9zQ >}}

Presentation at Elucidata's User Group Meeting on how our team evaluates and measures data quality while making high-dimensional biological data Findable, Accessible, Interoperable, and Reusable (FAIR).


## Role of data-curation with ontologies in biopharma R&D
{{< video https://www.youtube.com/watch?v=TSgNfaz2ZS0 >}}

Talk with [Pistoia Alliance](https://www.pistoiaalliance.org/), a non-profit alliance working to increase pre-competitive collaboration in life sciences industry. The talk highlights the role of data curation through ontologies to make data FAIR and to accelerate research.

## Product release: Curated multi-omics data atlas

{{< video https://www.youtube.com/watch?v=jobtBNCjmMo&t=964s >}}

Product release for Elucidata’s Liver OmixAtlas, the largest repository of ML-ready liver tissue-derived biological datasets. The goal is to provide a curated data source of scRNA-seq, RNA-seq, proteomics, and metabolomics data to accelerate drug discovery.
